import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    'from-orange-500',
    'to-red-600',
    'from-orange-600',
    'to-red-700',
    'bg-gradient-to-r',
    'bg-gradient-to-br',
    'from-gray-950',
    'via-gray-900',
    'to-gray-950',
    'from-gray-50',
    'via-white',
    'to-gray-50',
    'text-green-600',
    'text-green-400',
    'bg-green-50',
    'bg-green-950',
    'border-green-200',
    'border-green-800',
    'text-red-600',
    'text-red-400',
    'bg-red-50',
    'bg-red-950',
    'border-red-200',
    'border-red-800',
    'text-blue-600',
    'text-blue-400',
    'bg-blue-50',
    'bg-blue-950',
    'border-blue-200',
    'border-blue-800',
    'text-purple-600',
    'text-purple-400',
    'bg-purple-50',
    'bg-purple-950',
    'border-purple-200',
    'border-purple-800',
    'text-emerald-600',
    'text-emerald-400',
    'bg-emerald-50',
    'bg-emerald-950',
    'border-emerald-200',
    'border-emerald-800',
    'text-orange-600',
    'text-orange-400',
    'bg-orange-50',
    'bg-orange-950',
    'border-orange-200',
    'border-orange-800',
    'text-yellow-600',
    'text-yellow-400',
    'bg-yellow-50',
    'bg-yellow-950',
    'border-yellow-200',
    'border-yellow-800',
    'text-rose-600',
    'text-rose-400',
    'bg-rose-50',
    'bg-rose-950',
    'border-rose-200',
    'border-rose-800',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        orange: {
          500: "#FF6B35",
          600: "#E85A2C",
        },
        red: {
          600: "#DC2626",
          700: "#B91C1C",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;